const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_OUT_SUCESS: 'SIGN_OUT_SUCESS',
  SIGN_OUT_START: 'SIGN_OUT_START',

  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  // TODO: above are examples, customize later
};

export default UserActionTypes;
