const DirectoryActionTypes = {
  // TODO: add actions like friends status etc.
  SET_CURRENTLY_ACTIVE: 'SET_CURRENTLY_ACTIVE',
  TOGGLE_BACKDROP: 'TOGGLE_BACKDROP',
  CLOSE_BACKDROP: 'CLOSE_BACKDROP',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  CHANGE_ACTIVE_WINDOW: 'CHANGE_ACTIVE_WINDOW',
};

export default DirectoryActionTypes;
