const DirectoryActionTypes = {
  // TODO: add actions like friends status etc.
  SET_CURRENTLY_ACTIVE: 'SET_CURRENTLY_ACTIVE',
  TOGGLE_BACKDROP_INVITE: 'TOGGLE_BACKDROP_INVITE',
  TOGGLE_BACKDROP_GPCHAT: 'TOGGLE_BACKDROP_GPCHAT',
  CLOSE_BACKDROP_INVITE: 'CLOSE_BACKDROP_INVITE',
  CLOSE_BACKDROP_GPCHAT: 'CLOSE_BACKDROP_GPCHAT',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
  SET_LANGUAGE: 'SET_LANGUAGE',
  TOGGLE_PROFILE: 'TOGGLE_PROFILE',
  CLOSE_PROFILE: 'CLOSE_PROFILE',
  SET_CHATS_LIST: 'SET_CHATS_LIST',
};

export default DirectoryActionTypes;
